### ISSUE TITLE
failed to initialize channel on some cisco device

### ISSUE THREAD

**Issue by gaoxingliang** [gaoxingliang/JSch#2]
on some cisco device, the jsch channel fail to initialize on v0.1.54:
```
java.io.IOException: failed to initialize the channel.
at com.jcraft.jsch.Channel$1.init(Channel.java:242)
at com.jcraft.jsch.Channel$1.write(Channel.java:253)
at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
at java.io.BufferedWriter.flush(BufferedWriter.java:254)
```

This is caused by the check in 
```
com.jcraft.jsch.Channel#getOutputStream
                if (_buf.length - (14 + 0) - Session.buffer_margin <= 0) {
                    buffer = null;
                    packet = null;
                    throw new IOException("failed to initialize the channel.");
                }
```
The remote side may not has such large a remote packet maxium size.

This is caused by the buffer margin is increased between 0.1.53 and 0.1.54:
```

in v0.1.53:
static final int buffer_margin = 32 + // maximum padding length
20 + // maximum mac length
32;  // margin for deflater; deflater may inflate data

in v0.1.54:
com.jcraft.jsch.Session
static final int buffer_margin = 32 + // maximum padding length
64 + // maximum mac length
32;  // margin for deflater; deflater may inflate data


```

**Comment by gaoxingliang** [comment]
Already fixed in fix #3
